
MYLIBPATH = ['/home/hy/sw/install/lib',
             '/usr/lib']

MYCPPPATH = ['/home/hy/sw/install/include',
             '/home/hy/sw/install/include/boost-1_33',
            ]

USED_LIBS = ['db_cxx',
             'pthread',
             'ACE',]

SOURCES_FILES_1 = ['tds.cc', 'load_db.cc', 'rep.cc', 'worker.cc']


Program( 'rep_tds', 
          SOURCES_FILES_1, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )
