
MYLIBPATH = ['/home/hy/sw/install/lib',
             '/usr/lib']
MYCPPPATH = ['/home/hy/sw/install/include']
USED_LIBS = ['db_cxx',
             'pthread']

SOURCES_FILES = ['hello_world.cc']

SOURCES_FILES_1 = ['env_ex.cc']

Program( 'hello_world', 
          SOURCES_FILES, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )

Program( 'env_ex', 
          SOURCES_FILES_1, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )
