
MYLIBPATH = ['/home/hy/sw/install/lib',
             '/usr/lib']

MYCPPPATH = ['/home/hy/sw/install/include',
             '/home/hy/sw/install/include/boost-1_33',
            ]

USED_LIBS = ['db_cxx',
             'pthread',
             'ACE',]

SOURCES_FILES = ['cds.cc']
SOURCES_FILES_1 = ['tds.cc', 'load_db.cc']
SOURCES_FILES_2 = ['misc.cc']
SOURCES_FILES_3 = ['watcher.cc', 'load_db.cc']

Program( 'cds', 
          SOURCES_FILES, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )

Program( 'tds', 
          SOURCES_FILES_1, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )

Program( 'watcher', 
          SOURCES_FILES_3, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )

Program( 'misc', 
          SOURCES_FILES_2, 
          LIBS = USED_LIBS, 
          CPPPATH = MYCPPPATH,
          LIBPATH = MYLIBPATH )
